### ISSUE TITLE
mismatched package names between packages and playground

### ISSUE THREAD

**Issue by LoTwT** [developer-plus/mini-unocss#15]
It can't install dependencies correctly due to mismatched package names between packages and playground.

```bash
ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  

In playground: No matching version found for @developer-plus/mini-unocss-core@* inside the workspace
```

**Comment by TickHeart** [comment]
Sorry, it's our negligence.

**Comment by TickHeart** [comment]
The current version of the code is still very imperfect, and mini-unocss will be refactored soon, so you can stay tuned. @LoTwT

**Comment by masterX89** [comment]
found a solution to fix it by chaning `devDependencies` in _playground/package.json_ to
```json
"@developer-plus/mini-unocss-core": "../../packages:*",
"@developer-plus/mini-unocss-presets-default": "../../packages:*",
```
but use relative path here may be bad, I'm not very familiar with the way of writing here in package.json, there should be a more standardized way.

**Comment by Hongbusi** [comment]
咱直接中文交流了。

问题的原因是 `mini-unocss` 和 `preset-default` 发包的时候更改了包名，但是 playground 中忘记更改了。

建议你直接 fork 下来，相信一看就明白了。 @masterX89

**Comment by alexzhang1030** [comment]
> It can't install dependencies correctly due to mismatched package names between packages and playground.
> 
> ```shell
> ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  
> 
> In playground: No matching version found for @developer-plus/mini-unocss-core@* inside the workspace
> ```

@LoTwT Hongbusi 的回答已经解决了这个问题，谢谢你的贡献，后续我们会注意。这个 issue 我就关闭了，感谢
